spring:
  config:
    import: secrets.yaml
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USER_NAME}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: false
    #        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect

  #  jwt
  jwt:
    secret:
      key: ${JWT_SECRET}
  access:
    expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh:
    expiration: ${REFRESH_TOKEN_EXPIRATION}

#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    user: ${TEST_DB_USER_NAME}
#    password: ${TEST_DB_PASSWORD}
#    baseline-description: "init"
#    baseline-version: 0
#    bank code
bank:
  code: ${BANK_CODE}
  phone_number: ${BANK_PHONE_NUMBER}
  email: ${BANK_EMAIL}
  password: ${BANK_PASSWORD}

  #mail
mail:
  api:
    key: ${MAIL_API_KEY}
  url: ${MAIL_URL}
