spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true


  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        web-allow-others: false
