spring:
  profiles:
    active: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
#    Java Mail Sender
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  ##java mail sender
  #spring.mail.host=${MAIL_HOST}
  #spring.mail.port=${MAIL_PORT}
  #spring.mail.username=${MAIL_USERNAME}
  #spring.mail.password=${MAIL_PASSWORD}
  #spring.mail.properties.mail.smtp.auth=true
  #spring.mail.properties.mail.smtp.starttls.enable=true


#    fly way
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    user: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    baseline-description: "init"
#    baseline-version: 0

server:
  port: 8082

#logging:
#  level:
#    org:
#      springframework: DEBUG
#      hibernate: DEBUG

#  bank
bank:
  code: ${BANK_CODE}
  phone_number: ${BANK_PHONE_NUMBER}
  email: ${BANK_EMAIL}
  password: ${BANK_PASSWORD}

#mail
mail:
  api:
    key: ${MAIL_API_KEY}
  url: ${MAIL_URL}

#cloudinary
cloudinary:
  api:
    key: ${CLOUDINARY_KEY}
    secret: ${CLOUDINARY_SECRET}
  cloud:
    name: ${CLOUDINARY_NAME}

#  jwt
jwt:
  secret:
    key: ${JWT_SECRET}
access:
  expiration: ${ACCESS_TOKEN_EXPIRATION}
refresh:
  expiration: ${REFRESH_TOKEN_EXPIRATION}